[project]
name = "pdf2audiobook"
version = "0.1.0"
description = "Convert PDF to Audiobook using Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf2>=3.0.1",
    "pyttsx3>=2.97",
]
